"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { ResumeDocument } from "@/components/preview/ResumeDocument";
import { Button } from "@/components/ui";
import { decodeSharedResume, hydrateSharedResume } from "@/lib/share";
import { useResumeStore } from "@/lib/store";
import type { ResumeData } from "@/lib/types";

type LoadState = { status: "loading" } | { status: "error" } | { status: "ok"; data: ResumeData };

export default function SharePage() {
  const router = useRouter();
  const loadData = useResumeStore((s) => s.loadData);
  // Only used for this page's OWN UI text (button/error labels) — never to reinterpret the
  // shared resume's data, which keeps whatever locale it was generated with.
  const viewerLocale = useResumeStore((s) => s.locale);
  const pt = viewerLocale === "pt-br";
  const [state, setState] = useState<LoadState>({ status: "loading" });

  useEffect(() => {
    let cancelled = false;
    (async () => {
      const partial = await decodeSharedResume(window.location.hash);
      if (cancelled) return;
      setState(partial ? { status: "ok", data: hydrateSharedResume(partial) } : { status: "error" });
    })();
    return () => {
      cancelled = true;
    };
  }, []);

  function handleUseAsBase() {
    if (state.status !== "ok") return;
    loadData(state.data);
    toast.success(pt ? "Currículo aplicado ao seu formulário." : "Resume applied to your form.");
    router.push("/builder");
  }

  return (
    <div className="flex min-h-screen flex-col bg-slate-50 dark:bg-slate-950">
      <header className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 bg-white px-4 py-3 dark:border-slate-800 dark:bg-slate-900 sm:px-6">
        <Link href="/" className="text-sm font-semibold text-slate-900 dark:text-slate-100">
          ← resume-template
        </Link>
        {state.status === "ok" && (
          <Button type="button" onClick={handleUseAsBase}>
            {pt ? "Usar este currículo como base" : "Use this resume as a base"}
          </Button>
        )}
      </header>

      <main className="mx-auto w-full max-w-3xl flex-1 px-4 py-8 sm:px-6">
        {state.status === "loading" && (
          <p className="text-sm text-slate-500 dark:text-slate-400">
            {pt ? "Carregando currículo compartilhado…" : "Loading shared resume…"}
          </p>
        )}

        {state.status === "error" && (
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-800/60 dark:bg-amber-950/30 dark:text-amber-200">
            {pt
              ? "Não foi possível carregar esse link. Ele pode estar incompleto, corrompido, ou não ter sido gerado por este app."
              : "Couldn't load this link. It may be incomplete, corrupted, or not generated by this app."}
          </div>
        )}

        {state.status === "ok" && (
          <>
            <p className="mb-4 text-xs text-slate-400 dark:text-slate-500">
              {pt
                ? "Modo somente leitura — esses dados ainda não foram salvos no seu navegador. Clique em \"Usar este currículo como base\" acima se quiser editá-los."
                : 'Read-only mode — this data hasn\'t been saved to your browser yet. Click "Use this resume as a base" above if you want to edit it.'}
            </p>
            <div className="overflow-hidden rounded-lg border border-slate-200 shadow dark:border-slate-800">
              <ResumeDocument data={state.data} />
            </div>
          </>
        )}
      </main>
    </div>
  );
}
