"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { Wizard } from "@/components/Wizard";
import { TipsPanel } from "@/components/TipsPanel";
import { ScorePanel } from "@/components/ScorePanel";
import { JobMatchPanel } from "@/components/JobMatchPanel";
import { ResumeDocument } from "@/components/preview/ResumeDocument";
import { Button } from "@/components/ui";
import { getResumeData, useResumeStore } from "@/lib/store";
import { usePageEstimate } from "@/lib/usePageEstimate";
import type { ResumeData } from "@/lib/types";

type Tab = "form" | "checklist" | "job" | "tips";

export default function BuilderPage() {
  const locale = useResumeStore((s) => s.locale);
  const setLocale = useResumeStore((s) => s.setLocale);
  const reset = useResumeStore((s) => s.reset);
  const loadData = useResumeStore((s) => s.loadData);
  const [tab, setTab] = useState<Tab>("form");
  const fileInputRef = useRef<HTMLInputElement>(null);
  const previewRef = useRef<HTMLDivElement>(null);
  const pages = usePageEstimate(previewRef);

  function handleExport() {
    const data = getResumeData(useResumeStore.getState());
    const blob = new Blob([JSON.stringify(data, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "curriculo-backup.json";
    a.click();
    URL.revokeObjectURL(url);
  }

  function handleImportClick() {
    fileInputRef.current?.click();
  }

  async function handleImportChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    e.target.value = "";
    if (!file) return;
    try {
      const text = await file.text();
      const parsed = JSON.parse(text) as Partial<ResumeData>;
      if (typeof parsed !== "object" || parsed === null) throw new Error("invalid");
      loadData(parsed);
    } catch {
      alert(
        locale === "pt-br"
          ? "Não foi possível importar esse arquivo. Verifique se é um backup gerado por este app."
          : "Could not import this file. Make sure it's a backup generated by this app.",
      );
    }
  }

  const tabs: { id: Tab; label: string }[] = [
    { id: "form", label: locale === "pt-br" ? "Formulário" : "Form" },
    { id: "checklist", label: locale === "pt-br" ? "Checklist" : "Checklist" },
    { id: "job", label: locale === "pt-br" ? "Vaga" : "Job match" },
    { id: "tips", label: locale === "pt-br" ? "Dicas" : "Tips" },
  ];

  return (
    <div className="flex min-h-screen flex-col bg-slate-50">
      <header className="print:hidden flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 bg-white px-4 py-3 sm:px-6">
        <Link href="/" className="text-sm font-semibold text-slate-900">
          ← resume-template
        </Link>
        <div className="flex flex-wrap items-center gap-2">
          <div className="flex overflow-hidden rounded-md border border-slate-300">
            <button
              type="button"
              onClick={() => setLocale("pt-br")}
              className={
                "px-3 py-1.5 text-xs font-medium " +
                (locale === "pt-br"
                  ? "bg-slate-900 text-white"
                  : "bg-white text-slate-600 hover:bg-slate-50")
              }
            >
              PT-BR
            </button>
            <button
              type="button"
              onClick={() => setLocale("en")}
              className={
                "px-3 py-1.5 text-xs font-medium " +
                (locale === "en"
                  ? "bg-slate-900 text-white"
                  : "bg-white text-slate-600 hover:bg-slate-50")
              }
            >
              EN
            </button>
          </div>
          <Button variant="ghost" type="button" onClick={handleImportClick}>
            {locale === "pt-br" ? "Importar" : "Import"}
          </Button>
          <input
            ref={fileInputRef}
            type="file"
            accept="application/json"
            hidden
            onChange={handleImportChange}
          />
          <Button variant="ghost" type="button" onClick={handleExport}>
            {locale === "pt-br" ? "Backup (.json)" : "Backup (.json)"}
          </Button>
          <Button
            variant="ghost"
            type="button"
            onClick={() => {
              if (confirm(locale === "pt-br" ? "Limpar todos os dados?" : "Clear all data?")) {
                reset();
              }
            }}
          >
            {locale === "pt-br" ? "Limpar" : "Clear"}
          </Button>
          <Button type="button" onClick={() => window.print()}>
            {locale === "pt-br" ? "Baixar PDF" : "Download PDF"}
          </Button>
        </div>
      </header>

      <div className="print:hidden mx-auto grid w-full max-w-6xl flex-1 grid-cols-1 gap-6 px-4 py-6 sm:px-6 lg:grid-cols-[1fr_1fr]">
        <div>
          <div className="mb-4 flex flex-wrap gap-1.5">
            {tabs.map((t) => (
              <button
                key={t.id}
                type="button"
                onClick={() => setTab(t.id)}
                className={
                  "rounded-md px-3 py-1.5 text-xs font-medium " +
                  (tab === t.id
                    ? "bg-slate-900 text-white"
                    : "bg-slate-100 text-slate-600 hover:bg-slate-200")
                }
              >
                {t.label}
              </button>
            ))}
          </div>
          {tab === "form" && <Wizard />}
          {tab === "checklist" && <ScorePanel />}
          {tab === "job" && <JobMatchPanel />}
          {tab === "tips" && <TipsPanel />}
        </div>

        <div className="lg:sticky lg:top-6 lg:self-start">
          <div className="mb-2 flex items-center justify-between px-1">
            <span className="text-xs font-medium text-slate-500">
              {locale === "pt-br" ? "Prévia" : "Preview"}
            </span>
            <span
              className={
                "rounded-full px-2 py-0.5 text-[11px] font-medium " +
                (pages > 1
                  ? "bg-amber-100 text-amber-800"
                  : "bg-emerald-100 text-emerald-700")
              }
              title={
                locale === "pt-br"
                  ? "Estimativa — a contagem real pode variar um pouco na exportação."
                  : "Estimate — the actual count may vary slightly on export."
              }
            >
              {pages === 1
                ? locale === "pt-br"
                  ? "~1 página"
                  : "~1 page"
                : locale === "pt-br"
                  ? `~${pages} páginas — considere cortar conteúdo`
                  : `~${pages} pages — consider trimming content`}
            </span>
          </div>
          <div className="rounded-lg border border-slate-200 bg-slate-100 p-4">
            <div
              ref={previewRef}
              className="max-h-[calc(100vh-8rem)] overflow-y-auto rounded shadow"
            >
              <ResumeDocument />
            </div>
          </div>
        </div>
      </div>

      <div className="hidden print:block">
        <ResumeDocument printable />
      </div>
    </div>
  );
}
