"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { useShallow } from "zustand/react/shallow";
import { toast } from "sonner";
import { Wizard } from "@/components/Wizard";
import { TipsPanel } from "@/components/TipsPanel";
import { ScorePanel } from "@/components/ScorePanel";
import { JobMatchPanel } from "@/components/JobMatchPanel";
import { ResumeDocument } from "@/components/preview/ResumeDocument";
import { PdfReviewModal } from "@/components/PdfReviewModal";
import { ConfirmModal } from "@/components/ConfirmModal";
import { ShareModal } from "@/components/ShareModal";
import { Button } from "@/components/ui";
import { getResumeData, useResumeStore } from "@/lib/store";
import { A4_HEIGHT_PX, usePageEstimate } from "@/lib/usePageEstimate";
import { extractPdfText, parseResumeText } from "@/lib/pdfImport";
import type { ResumeData } from "@/lib/types";

type Tab = "form" | "checklist" | "job" | "tips";

export default function BuilderPage() {
  const locale = useResumeStore((s) => s.locale);
  const setLocale = useResumeStore((s) => s.setLocale);
  const reset = useResumeStore((s) => s.reset);
  const loadData = useResumeStore((s) => s.loadData);
  const [tab, setTab] = useState<Tab>("form");
  const [importingPdf, setImportingPdf] = useState(false);
  const [pdfReview, setPdfReview] = useState<Partial<ResumeData> | null>(null);
  const [confirmingClear, setConfirmingClear] = useState(false);
  const [sharing, setSharing] = useState(false);
  // See ScorePanel.tsx / JobMatchPanel.tsx — getResumeData returns a new object every call, so
  // it needs useShallow or React logs a getSnapshot-consistency warning on every render.
  const resumeData = useResumeStore(useShallow((s) => getResumeData(s)));
  const jsonInputRef = useRef<HTMLInputElement>(null);
  const pdfInputRef = useRef<HTMLInputElement>(null);
  const previewRef = useRef<HTMLDivElement>(null);
  const pages = usePageEstimate(previewRef);

  function handleExport() {
    const data = getResumeData(useResumeStore.getState());
    const blob = new Blob([JSON.stringify(data, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "curriculo-backup.json";
    a.click();
    URL.revokeObjectURL(url);
  }

  async function handleJsonImportChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    e.target.value = "";
    if (!file) return;
    try {
      const text = await file.text();
      const parsed = JSON.parse(text) as Partial<ResumeData>;
      if (typeof parsed !== "object" || parsed === null) throw new Error("invalid");
      loadData(parsed);
      toast.success(
        locale === "pt-br" ? "Backup importado com sucesso." : "Backup imported successfully.",
      );
    } catch {
      toast.error(
        locale === "pt-br"
          ? "Não foi possível importar esse arquivo. Verifique se é um backup gerado por este app."
          : "Could not import this file. Make sure it's a backup generated by this app.",
      );
    }
  }

  async function handlePdfImportChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    e.target.value = "";
    if (!file) return;

    setImportingPdf(true);
    try {
      const text = await extractPdfText(file);
      const parsed = parseResumeText(text);
      setPdfReview(parsed);
    } catch (err) {
      console.error("PDF import failed:", err);
      toast.error(
        locale === "pt-br"
          ? "Não foi possível ler esse PDF. Tente um arquivo com texto selecionável (não uma imagem escaneada)."
          : "Could not read this PDF. Try a file with selectable text (not a scanned image).",
      );
    } finally {
      setImportingPdf(false);
    }
  }

  const tabs: { id: Tab; label: string }[] = [
    { id: "form", label: locale === "pt-br" ? "Formulário" : "Form" },
    { id: "checklist", label: locale === "pt-br" ? "Checklist" : "Checklist" },
    { id: "job", label: locale === "pt-br" ? "Vaga" : "Job match" },
    { id: "tips", label: locale === "pt-br" ? "Dicas" : "Tips" },
  ];

  return (
    <div className="flex min-h-screen flex-col bg-slate-50 dark:bg-slate-950">
      <header className="print:hidden flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 bg-white px-4 py-3 dark:border-slate-800 dark:bg-slate-900 sm:px-6">
        <Link href="/" className="text-sm font-semibold text-slate-900 dark:text-slate-100">
          ← resume-template
        </Link>
        <div className="flex flex-wrap items-center gap-2">
          <Link
            href="/feed"
            className="rounded-md px-3 py-1.5 text-sm font-medium text-slate-600 hover:bg-slate-100 dark:text-slate-400 dark:hover:bg-slate-800"
          >
            {locale === "pt-br" ? "Notícias e vagas" : "News and jobs"}
          </Link>
          <div className="flex overflow-hidden rounded-md border border-slate-300 dark:border-slate-600">
            <button
              type="button"
              onClick={() => setLocale("pt-br")}
              className={
                "px-3 py-1.5 text-xs font-medium " +
                (locale === "pt-br"
                  ? "bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900"
                  : "bg-white text-slate-600 hover:bg-slate-50 dark:bg-slate-800 dark:text-slate-400 dark:hover:bg-slate-700")
              }
            >
              PT-BR
            </button>
            <button
              type="button"
              onClick={() => setLocale("en")}
              className={
                "px-3 py-1.5 text-xs font-medium " +
                (locale === "en"
                  ? "bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900"
                  : "bg-white text-slate-600 hover:bg-slate-50 dark:bg-slate-800 dark:text-slate-400 dark:hover:bg-slate-700")
              }
            >
              EN
            </button>
          </div>
          <Button
            variant="ghost"
            type="button"
            disabled={importingPdf}
            onClick={() => pdfInputRef.current?.click()}
          >
            {importingPdf
              ? locale === "pt-br"
                ? "Lendo PDF…"
                : "Reading PDF…"
              : locale === "pt-br"
                ? "Importar PDF"
                : "Import PDF"}
          </Button>
          <input
            ref={pdfInputRef}
            type="file"
            accept="application/pdf"
            hidden
            onChange={handlePdfImportChange}
          />
          <Button variant="ghost" type="button" onClick={() => jsonInputRef.current?.click()}>
            {locale === "pt-br" ? "Importar backup" : "Import backup"}
          </Button>
          <input
            ref={jsonInputRef}
            type="file"
            accept="application/json"
            hidden
            onChange={handleJsonImportChange}
          />
          <Button variant="ghost" type="button" onClick={handleExport}>
            {locale === "pt-br" ? "Backup (.json)" : "Backup (.json)"}
          </Button>
          <Button variant="ghost" type="button" onClick={() => setSharing(true)}>
            {locale === "pt-br" ? "Compartilhar" : "Share"}
          </Button>
          <Button variant="ghost" type="button" onClick={() => setConfirmingClear(true)}>
            {locale === "pt-br" ? "Limpar" : "Clear"}
          </Button>
          <Button type="button" onClick={() => window.print()}>
            {locale === "pt-br" ? "Baixar PDF" : "Download PDF"}
          </Button>
        </div>
      </header>

      <div className="print:hidden mx-auto grid w-full max-w-6xl flex-1 grid-cols-1 gap-6 px-4 py-6 sm:px-6 lg:grid-cols-[1fr_1fr]">
        <div>
          <div className="mb-4 flex flex-wrap gap-1.5">
            {tabs.map((t) => (
              <button
                key={t.id}
                type="button"
                onClick={() => setTab(t.id)}
                className={
                  "rounded-md px-3 py-1.5 text-xs font-medium " +
                  (tab === t.id
                    ? "bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900"
                    : "bg-slate-100 text-slate-600 hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-400 dark:hover:bg-slate-700")
                }
              >
                {t.label}
              </button>
            ))}
          </div>
          {tab === "form" && <Wizard />}
          {tab === "checklist" && <ScorePanel />}
          {tab === "job" && <JobMatchPanel />}
          {tab === "tips" && <TipsPanel />}
        </div>

        <div className="lg:sticky lg:top-6 lg:self-start">
          <div className="mb-2 flex items-center justify-between px-1">
            <span className="text-xs font-medium text-slate-500 dark:text-slate-400">
              {locale === "pt-br" ? "Prévia" : "Preview"}
            </span>
            <span
              className={
                "rounded-full px-2 py-0.5 text-[11px] font-medium " +
                (pages > 1
                  ? "bg-amber-100 text-amber-800 dark:bg-amber-950/50 dark:text-amber-300"
                  : "bg-emerald-100 text-emerald-700 dark:bg-emerald-950/50 dark:text-emerald-300")
              }
              title={
                locale === "pt-br"
                  ? "Estimativa — a contagem real pode variar um pouco na exportação."
                  : "Estimate — the actual count may vary slightly on export."
              }
            >
              {pages === 1
                ? locale === "pt-br"
                  ? "~1 página"
                  : "~1 page"
                : locale === "pt-br"
                  ? `~${pages} páginas — considere cortar conteúdo`
                  : `~${pages} pages — consider trimming content`}
            </span>
          </div>
          <div className="rounded-lg border border-slate-200 bg-slate-100 p-4 dark:border-slate-700 dark:bg-slate-800">
            <div className="max-h-[calc(100vh-8rem)] overflow-y-auto rounded shadow">
              <div className="relative">
                <div ref={previewRef}>
                  <ResumeDocument />
                </div>
                {Array.from({ length: pages - 1 }).map((_, i) => (
                  <div
                    key={i}
                    className="pointer-events-none absolute inset-x-0 border-t-2 border-dashed border-red-400 dark:border-red-500"
                    style={{ top: (i + 1) * A4_HEIGHT_PX }}
                  >
                    <span className="absolute right-2 top-1 rounded bg-red-100 px-1.5 py-0.5 text-[10px] font-medium text-red-700 dark:bg-red-950/60 dark:text-red-300">
                      {locale === "pt-br" ? `Página ${i + 2}` : `Page ${i + 2}`}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="hidden print:block">
        <ResumeDocument printable />
      </div>

      {pdfReview && (
        <PdfReviewModal
          data={pdfReview}
          locale={locale}
          onCancel={() => setPdfReview(null)}
          onApply={(selected) => {
            loadData(selected);
            setPdfReview(null);
            setTab("form");
            toast.success(
              locale === "pt-br" ? "Dados do PDF aplicados ao formulário." : "PDF data applied to the form.",
            );
          }}
        />
      )}

      {sharing && (
        <ShareModal data={resumeData} locale={locale} onClose={() => setSharing(false)} />
      )}

      {confirmingClear && (
        <ConfirmModal
          title={locale === "pt-br" ? "Limpar todos os dados?" : "Clear all data?"}
          message={
            locale === "pt-br"
              ? "Essa ação apaga tudo que você preencheu no formulário. Não pode ser desfeita."
              : "This clears everything you've filled in the form. It can't be undone."
          }
          confirmLabel={locale === "pt-br" ? "Limpar" : "Clear"}
          cancelLabel={locale === "pt-br" ? "Cancelar" : "Cancel"}
          onCancel={() => setConfirmingClear(false)}
          onConfirm={() => {
            reset();
            setConfirmingClear(false);
            toast.success(locale === "pt-br" ? "Dados limpos." : "Data cleared.");
          }}
        />
      )}
    </div>
  );
}
